original_tuple = (10, 20, 30, 40, 50)
print(f"Original tuple is {original_tuple}")
print(f"Length of original tuple is {len(original_tuple)}")
print(f"Element at index 3 is {original_tuple[3]}")
print(f"Last element of original tuple is {original_tuple[-1]}")
new_list = list(original_tuple)
new_list.append(60)
new_tuple = tuple(new_list)
print(new_tuple)
